In [1]:
import numpy as np
import pandas as pd
import random
import string

In [2]:
"""
1. define name list and include values ranging from 10 to 100 with step value 10
2. create a dataframe multiplying each name to 10 times and reset the index
"""
names = [x for x in range(10,101,10)]
df = pd.DataFrame({'name':names*10}).sort_values('name').reset_index()

In [3]:
# drop the index column
df.drop(columns=['index'],inplace=True)

In [4]:
""" 
define the transform function palidromeAndNonPalindromeData(k) with the following functionalities
1. 

"""
def palidromeAndNonPalindromeData(k):
    i = k.iloc[0]
    l = len(k)
    a = [''.join(random.choices(string.ascii_letters,k=i)) for x in range(l//2)]
    b = [ y+y[::-1] for y in [''.join(random.choices(string.ascii_letters,k=i//2)) for x in range(l-(l//2))]] if i%2==0 else [ y+random.choice(string.ascii_letters)+y[::-1] for y in [''.join(random.choices(string.ascii_letters,k=(l-l//2))) for x in range(5)]]
    return a + b;

In [5]:
df['value'] = df.groupby('name')['name'].transform(palidromeAndNonPalindromeData)

In [6]:
df['expected'] = df['value'].apply(lambda x: x[::-1])

In [7]:
df.head(20)

    name                 value              expected
0     10            KYhijQXMug            guMXQjihYK
1     10            dqcXcDETML            LMTEDcXcqd
2     10            NfcsqJvUeo            oeUvJqscfN
3     10            ArxKzXyYkd            dkYyXzKxrA
4     10            AxmXZxVklo            olkVxZXmxA
5     10            bvBIAAIBvb            bvBIAAIBvb
6     10            ejkMyyMkje            ejkMyyMkje
7     10            qYYpWWpYYq            qYYpWWpYYq
8     10            KZDPPPPDZK            KZDPPPPDZK
9     10            NYpHFFHpYN            NYpHFFHpYN
10    20  jDBtyRgPPlfVBsznuvBQ  QBvunzsBVflPPgRytBDj
11    20  TbGxeXQnYVidwfVpljDu  uDjlpVfwdiVYnQXexGbT
12    20  SmHHJWkMTEqivFtdoTMC  CMTodtFviqETMkWJHHmS
13    20  paqMlAPSORzdkZsKabfJ  JfbaKsZkdzROSPAlMqap
14    20  GlNDMAGDRjLuNzhAlFeN  NeFlAhzNuLjRDGAMDNlG
15    20  ktqYBwBvDvvDvBwBYqtk  ktqYBwBvDvvDvBwBYqtk
16    20  LbqhPtYTJggJTYtPhqbL  LbqhPtYTJggJTYtPhqbL
17    20  fOloNXyMqwwqMyXNolOf  fOloNXyMqwwqMyXNolOf
18    20  VdoVIlwgnTTngwlIVodV  VdoVIlwgnTTngwlIVodV
19    20  CsqJwnFkUwwUkFnwJqsC  CsqJwnFkUwwUkFnwJqsC

In [8]:
df.rename(columns={'value':'input'}, inplace=True)

In [9]:
df.head()

   name       input    expected
0    10  KYhijQXMug  guMXQjihYK
1    10  dqcXcDETML  LMTEDcXcqd
2    10  NfcsqJvUeo  oeUvJqscfN
3    10  ArxKzXyYkd  dkYyXzKxrA
4    10  AxmXZxVklo  olkVxZXmxA